=== A-Gonzalez99/ProyectoForestal/prediccionForestal.dtd
<!ELEMENT Proyecto (reservaNatural+)>
  <!ELEMENT reservaNatural (Nombre, Provincia, Zona+)>
  <!ATTLIST reservaNatural Provincia CDATA #PCDATA> 

  <!ELEMENT Nombre (#PCDATA)>
  <!ELEMENT Provincia (#PCDATA)>
  <!ELEMENT Zona (Datos)>
  <!ATTLIST Zona Municipio CDATA #PCDATA> 

  <!ELEMENT Datos (Clima, Tierra)>
  <!ELEMENT Clima (Atmosfera)>
  <!ELEMENT Atmosfera (Temperatura, Precipitaciones, Vientos, Nubes)>
  <!ELEMENT Temperatura (#PCDATA)>
  <!ELEMENT Precipitaciones (Tipo, velocidad, Direccion, Cantidad)>
  <!ELEMENT Tipo (#PCDATA)>
  <!ELEMENT velocidad (#PCDATA)>
  <!ELEMENT Direccion (#PCDATA)>
  <!ELEMENT Cantidad (#PCDATA)>
  <!ELEMENT Vientos (velocidad, Direccion)>
  <!ELEMENT velocidad (#PCDATA)>
  <!ELEMENT Direccion (#PCDATA)>
  <!ELEMENT Nubes (Masa)>
  <!ELEMENT Masa (#PCDATA)>
  <!ELEMENT Tierra (Humedad, Consistencia, VegetacionSeca)>
  <!ELEMENT Humedad (#PCDATA)>
  <!ELEMENT Consistencia (#PCDATA)>
  <!ELEMENT VegetacionSeca (#PCDATA)>

=== A-Gonzalez99/ProyectoForestal/prediccionForestal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Proyecto SYSTEM "prediccionForestal.dtd">

<Proyecto>
    <reservaNatural Provincia="Santa Cruz de Tenerife">
        <Nombre>Las Lagunetas</Nombre>
            <Zona Municipio="Candelaria">
                <Datos>
                        <Clima>
                            <Atmosfera> 
                                <Temperatura>30</Temperatura>
                                <Precipitaciones>
                                    <Tipo>Lluvia</Tipo>
                                    <velocidad>8</velocidad>
                                    <Direccion>45,0,1</Direccion>
                                    <Cantidad>200</Cantidad>
                                </Precipitaciones>

                                <Vientos>
                                    <velocidad>3</velocidad>
                                    <Direccion>90,0,21</Direccion>
                                </Vientos>

                                <Nubes>
                                    <Masa>389</Masa>
                                </Nubes>

                            </Atmosfera>
                        </Clima>

                        <Tierra>
                            <Humedad>16</Humedad>
                            <Consistencia>60</Consistencia>
                            <VegetacionSeca>12</VegetacionSeca>
                        </Tierra>
                </Datos>
            </Zona>

            <Zona Municipio="El Rosario">
                <Datos>
                        <Clima>
                            <Atmosfera> 
                                <Temperatura>30</Temperatura>
                                <Precipitaciones>
                                    <Tipo>Lluvia</Tipo>
                                    <velocidad>8</velocidad>
                                    <Direccion>45,0,1</Direccion>
                                    <Cantidad>200</Cantidad>
                                </Precipitaciones>

                                <Vientos>
                                    <velocidad>3</velocidad>
                                    <Direccion>90,0,21</Direccion>
                                </Vientos>

                                <Nubes>
                                    <Masa>389</Masa>
                                </Nubes>

                            </Atmosfera>
                        </Clima>

                        <Tierra>
                            <Humedad>16</Humedad>
                            <Consistencia>60</Consistencia>
                            <VegetacionSeca>12</VegetacionSeca>
                        </Tierra>
                </Datos>
            </Zona>    
    </reservaNatural>

    <reservaNatural Provincia="Las Palmas">
        <Nombre>Tamadaba</Nombre>
            <Zona Municipio="Artenara">
                <Datos>
                        <Clima>
                            <Atmosfera> 
                                <Temperatura>30</Temperatura>
                                <Precipitaciones>
                                    <Tipo>Lluvia</Tipo>
                                    <velocidad>8</velocidad>
                                    <Direccion>45,0,1</Direccion>
                                    <Cantidad>200</Cantidad>
                                </Precipitaciones>

                                <Vientos>
                                    <velocidad>3</velocidad>
                                    <Direccion>90,0,21</Direccion>
                                </Vientos>

                                <Nubes>
                                    <Masa>389</Masa>
                                </Nubes>

                            </Atmosfera>
                        </Clima>

                        <Tierra>
                            <Humedad>16</Humedad>
                            <Consistencia>60</Consistencia>
                            <VegetacionSeca>12</VegetacionSeca>
                        </Tierra>
                </Datos>
            </Zona>

            <Zona Municipio="Agaete">
                <Datos>
                        <Clima>
                            <Atmosfera> 
                                <Temperatura>30</Temperatura>
                                <Precipitaciones>
                                    <Tipo>Lluvia</Tipo>
                                    <velocidad>8</velocidad>
                                    <Direccion>45,0,1</Direccion>
                                    <Cantidad>200</Cantidad>
                                </Precipitaciones>

                                <Vientos>
                                    <velocidad>3</velocidad>
                                    <Direccion>90,0,21</Direccion>
                                </Vientos>

                                <Nubes>
                                    <Masa>389</Masa>
                                </Nubes>

                            </Atmosfera>
                        </Clima>

                        <Tierra>
                            <Humedad>16</Humedad>
                            <Consistencia>60</Consistencia>
                            <VegetacionSeca>12</VegetacionSeca>
                        </Tierra>
                </Datos>
            </Zona>    
    </reservaNatural>
</Proyecto>
